<a href="https://colab.research.google.com/github/mssamoilenko/-_optuna/blob/main/%20%D0%A1%D0%B0%D0%BC%D0%BE%D0%B9%D0%BB%D0%B5%D0%BD%D0%BA%D0%BE%D0%94%D0%97_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/HalyshAnton/IT-Step-Pyton-AI/main/module3/data/House_Rent_Dataset.csv", index_col="Unnamed: 0")

[Інформація про дані](https://www.kaggle.com/datasets/iamsouravbanerjee/house-rent-prediction-dataset)

In [4]:
df.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2.0,10000.0,1100.0,Ground out of 2,NaN,NaN,Kolkata,Unfurnished,Bachelors/Family,2.0,Contact Owner
1,2022-05-13,2.0,20000.0,800.0,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1.0,NaN
2,2022-05-16,2.0,17000.0,1000.0,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1.0,Contact Owner
3,2022-07-04,2.0,10000.0,800.0,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1.0,Contact Owner
4,NaN,2.0,7500.0,850.0,1 out of 2,Carpet Area,NaN,Kolkata,Unfurnished,Bachelors,1.0,Contact Owner

In [5]:
df = df[['Size', 'Furnishing Status', 'City', 'Rent']]
df.head()

     Size Furnishing Status     City     Rent
0  1100.0       Unfurnished  Kolkata  10000.0
1   800.0    Semi-Furnished  Kolkata  20000.0
2  1000.0    Semi-Furnished  Kolkata  17000.0
3   800.0       Unfurnished  Kolkata  10000.0
4   850.0       Unfurnished  Kolkata   7500.0

In [9]:
df.columns = df.columns.str.lower()

# Завдання 1
Очистіть дані від викидів, розділіть на тренувальну та тестову чатини. Цільова ознака `Rent`

In [13]:
df.shape

(4746, 4)

In [11]:
Q1 = df['rent'].quantile(0.25)
Q3 = df['rent'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df_cleaned = df[(df['rent'] >= lower_bound) & (df['rent'] <= upper_bound)]

df_cleaned

        size furnishing status       city     rent
0     1100.0       Unfurnished    Kolkata  10000.0
1      800.0    Semi-Furnished    Kolkata  20000.0
2     1000.0    Semi-Furnished    Kolkata  17000.0
3      800.0       Unfurnished    Kolkata  10000.0
4      850.0       Unfurnished    Kolkata   7500.0
...      ...               ...        ...      ...
4741  1000.0    Semi-Furnished  Hyderabad  15000.0
4742  2000.0    Semi-Furnished  Hyderabad  29000.0
4743  1750.0    Semi-Furnished  Hyderabad  35000.0
4744  1500.0    Semi-Furnished  Hyderabad  45000.0
4745  1000.0       Unfurnished  Hyderabad  15000.0

[3895 rows x 4 columns]

# Завдання 2
Створіть Pipeline для обробки числових стовпчиків(заповнення пропусків)

# Завдання 3
Створіть Pipeline для обробки категоріальних стовпчиків(заповнення пропусків та кодування)

# Завдання 4
Об'єднайте попередні Pipeline в один ColumnTransformer

# Завдання 5
Створіть остаточну модель та натренуйте її

# Завдання 6
Виведіть основні метрики моделі

# Завдання 7
Спрогнозуйте ціну будинку

In [ ]:
data = pd.DataFrame({'Size': [900],
                     'Furnishing Status': ['Semi-Furnished'],
                     'City': ['Mumbai']})

data

   Size Furnishing Status    City
0   900    Semi-Furnished  Mumbai